services:
    loki:
        image: grafana/loki:2.9.1
        container_name: loki
        ports:
            - "3100:3100" # Loki's HTTP API
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - ./src/config/loki-config.yml:/etc/loki/local-config.yaml
            - ./src/data/loki:/data/loki
        networks:
            - observability

    grafana:
        image: grafana/grafana:9.5.2
        container_name: grafana
        ports:
            - "3000:3000" # Grafana's web UI
        volumes:
            - ./src/data/grafana:/var/lib/grafana
        networks:
            - observability
        depends_on:
            - loki

volumes:
    grafana-data: # Persistent storage for Grafana
        driver: local

networks:
    observability:
        driver: bridge
