auth_enabled: false

server:
    http_listen_port: 3100

ingester:
    lifecycler:
        ring:
            kvstore:
                store: inmemory
            replication_factor: 1
        final_sleep: 0s

schema_config:
    configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
              prefix: index_
              period: 24h

storage_config:
    filesystem:
        directory: /data/loki/chunks
    boltdb_shipper:
        active_index_directory: /data/loki/indices
        cache_location: /data/loki/cache
        shared_store:
compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: filesystem

limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
