server:
    http_listen_port: 9080

positions:
    filename: /tmp/positions.yaml # Keeps track of which logs were already read

clients:
    - url: http://localhost:3100/loki/api/v1/push # Loki endpoint

scrape_configs:
    - job_name: node_app_logs
      static_configs:
          - targets:
                - localhost
            labels:
                job: node-app
                env: production
                __path__: ../../app.log
